package mapreduce

import (
	"bufio"
	"encoding/binary"
	"hash/fnv"
	"io"
	"io/ioutil"
	"os"
)

func doMap(
	jobName string, // the name of the MapReduce job
	mapTask int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(filename string, contents string) []KeyValue,
) {
	//
	// doMap manages one map task: it should read one of the input files
	// (inFile), call the user-defined map function (mapF) for that file's
	// contents, and partition mapF's output into nReduce intermediate files.
	//
	// There is one intermediate file per reduce task. The file name
	// includes both the map task number and the reduce task number. Use
	// the filename generated by reduceName(jobName, mapTask, r)
	// as the intermediate file for reduce task r. Call ihash() (see
	// below) on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
	// Your code here (Part I).

	// read file data
	inData, err := ioutil.ReadFile(inFile)
	if err != nil {
		panic(err)
	}

	// read the user map function
	var kvs []KeyValue = mapF(inFile, string(inData));

	// get the output file
	var splitKvs [][]KeyValue = make([][]KeyValue, nReduce, nReduce)
	for _, kv := range kvs {
		var reduceIdx = ihash(kv.Key) % nReduce
		if splitKvs[reduceIdx] == nil {
			splitKvs[reduceIdx] = make([]KeyValue, 0)
		}
		splitKvs[reduceIdx] = append(splitKvs[reduceIdx], kv)
	}

	//write the output file
	for reduceTask := 0; reduceTask < nReduce; reduceTask ++ {
		reduceFile := reduceName(jobName, mapTask, reduceTask)
		writeReduceData(reduceFile, splitKvs[reduceTask])
	}

}

func writeReduceData(reduceFile string, kvs []KeyValue)  {
	//create file
	f, err := os.Create(reduceFile)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	//write data
	w := bufio.NewWriter(f)
	for _, kv := range kvs {
		serialization(w, kv)
	}
	//flush and close file
	w.Flush()
}

func serialization(w io.Writer, kv KeyValue)  {
	var keyLen uint32 = uint32(len(kv.Key))
	var valLen uint32 = uint32(len(kv.Value))

	binary.Write(w, binary.LittleEndian, keyLen)
	binary.Write(w, binary.LittleEndian, valLen)
	if len(kv.Key) > 0 {
		w.Write([]byte(kv.Key))
	}
	if len(kv.Value) > 0 {
		w.Write([]byte(kv.Value))
	}
}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
